#!/bin/sh
if [ -f "/etc/hopla.cloud-roles" ]
then
            printf "\n"
            printf "Deployed OneClick apps (supported by hopla.cloud):"
            printf "\n"
            cat /etc/hopla.cloud-roles
    fi
